### ISSUE TITLE
setup translations for App Store descriptions

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios-app#105]
We need to set up an easy way to manage (and in the future crowdsource) the translations for the app descriptions in the App Store.

Ideal way: 

@Dianaaiym should be able to keep track of the descriptions in the same file that she currently users for the text strings in the app. When the app is built and uploaded to App Store the fastlane should be able to identify that string in the file and use the translated variations to correctly popular descriptions for each language.If that not possible then a separate file would work as well.

**Comment by uberkerim** [comment]
App description will be stored in Fastlane folders together with translations. Since location as well as format of file will be different from file containing interface strings, we need to setup new Crowding project for it.
So, @mNizhurin will setup folders and source file, and I will setup Crowdin project for them.

**Comment by uberkerim** [comment]
Done.

**Comment by uberkerim** [comment]
https://crwd.in/bank-wallet-app-description
